# Generated by Django 4.0.2 on 2022-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
