# Generated by Django 4.0.2 on 2022-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_rename_nick_name_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
